services:
  tournament-bot:
    build: .
    container_name: tournament-bot
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./data:/app/data

volumes:
  tournament-data:
